name: Latest Twitter Tweets
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITTER"
          feed_list: "https://nitter.net/search/rss?f=tweets&q=walkxtweet"
          commit_message: "Updated with the latest tweets"
          committer_username: "twitter-bot"
          committer_email: "twitter-bot@example.com"
